@include('partials.header')
<body>
	@include('partials.navbar')
    <main>
        @yield('main')
    </main>
    @include('partials.footer')
    @yield('javascript')
</body>
@include('partials.footer_script')
